### ISSUE TITLE
[BUG] Runaway output in yarn build

### ISSUE THREAD

**Issue by Samantha-uk** [ojkelly/yarn.build#48] opened 2020-12-16 15:29 UTC
**Describe the bug**
I am sometimes (_the worst possible situation_) seeing extraneous output (_I think_) in `yarn build`.

**To Reproduce**
1. Run command 'yarn build'

**Expected behavior**
Output like this
```
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.94s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zigzag-plugin-data-file (builder) 1.94s
➤ YN0000: │ [3] home-assistant/zigzag/modules/data/plugins/gen@samantha-uk/zigzag-data-plugin-gen (builder) 1.94s
➤ YN0000: │ [4] home-assistant/zigzag/modules/layout/plugins/d3@samantha-uk/zigzag-plugin-layout-d3 (builder) 2.21s
➤ YN0000: └ [3:0/9] 6.15s
```

**What I see from time to time**
```
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/data/core@samantha-uk/zigzag-data
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.14s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.39s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.47s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.61s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.70s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.79s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.88s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 0.97s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.06s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.15s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.24s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.33s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.42s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.51s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.60s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.69s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.78s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.87s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 1.96s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.05s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.15s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.24s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.33s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.42s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.51s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.60s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.69s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.78s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.87s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 2.97s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.06s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.15s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.24s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.33s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.42s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.51s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/file@samantha-uk/zig
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.66s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/gen@samantha-uk/zigz
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-grapher (builder) 3.76s
➤ YN0000: │ [2] home-assistant/zigzag/modules/data/plugins/gen@samantha-uk/zigz
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/modules/grapher@samantha-uk/zigzag-graphe
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: │ [1] home-assistant/zigzag/components/zigzag-wc@samantha-uk/zigzag-w
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ┌ Run build for All
➤ YN0000: ➤ Run [ build finished ]
➤ YN0000: [9:0/9]
➤ YN0000: Done in 18s 311ms
  ~/github/one on   main *1 +1325 !121 ?111                                                         took  19s with samantha@svr-development at  15:03:04
❯
```

**Desktop (please complete the following information):**
OS: Debian Buster
Yarn: v2.4.0-git.20201213.364c3992
Yarn Build: v0.9.1
Node: 14.15.1

**Additional context**
Happy to try to track this down and PR a fix ... if you can give me some guidance as to where I might start looking ...

**Comment by ojkelly** [comment] 2020-12-16 22:15
This is a bug that occurs when resizing the terminal, while outputting progress.

This one is a bit tricky and something I haven't approached yet. But definitely a bug that would be really nice to solve.

The code for it is here https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/supervisor/index.ts#L724

Essentially, for each available runItem we output its status. This is done by overwriting the previous n lines, where n is the number of threads.

I think the issue is somewhere in the fact that when resized during output, something changes in an unexpected way.

It might be the line count increases, or something similar.

I think we probably need to check for a resize event, and handle it.

Similarly, part of the fix might be making the progress output aware of the size of the terminal, and formatting the output to fit within (ie, probably by truncating the start of the package name).

**Comment by Samantha-uk** [comment] 2020-12-17 21:40
Interesting ...
I can confirm that if I reduce the size of my terminal during a run the issues appears.
I actually run one monitor with quarter size terminals and one with full size ... both with similar font size.
On the smaller terminals the issues appears.
From a little bit of playing it seems to occur if `build` output "overflows" the terminal width.
For example, this width acts as desired.
![image](https://user-images.githubusercontent.com/45871296/102546693-ed529980-40af-11eb-9658-62ca6c106ef2.png)

But if I reduce the width of the terminal to one less character, it consistently demonstrates the issue.
![image](https://user-images.githubusercontent.com/45871296/102546947-50dcc700-40b0-11eb-87c9-0c3edf310bec.png)

**Comment by Samantha-uk** [comment] 2020-12-17 21:40
Ooops ... clicked wrong button lol. Tired after a long shift on the unit.

**Comment by Samantha-uk** [comment] 2020-12-17 22:10
I think it may have its root here
https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/supervisor/index.ts#L700
It determines the number of lines displayed based on how many `\n' it finds and in this situation there are more lines than that ...

But how to correct it ...  what you suggest about truncation would work, we could query the `writeStream.columns` when we start (_and even be ultra sexy by modifying it on the `resize` event_).

**Comment by ojkelly** [comment] 2020-12-17 23:02
Yeah that makes sense.

Let me know if you want to have a go at fixing it (it'd be much appreciated), otherwise I think i might be able to tackle it next week.

**Comment by Samantha-uk** [comment] 2020-12-18 21:33
I'll give it a go 😃

**Comment by ojkelly** [comment] 2020-12-27 04:08
thanks for the work on #53. I'll close this ticket now. The build output could still be improved to be size aware, but it no longer runs away being all messy :D

**Closed by ojkelly** 2020-12-27 04:08 UTC
Labels: bug
